### ISSUE TITLE
Marshaling/Unmarshaling PDU to/from JSON

### ISSUE THREAD

**Issue by cesar0094** [fiorix/go-smpp#18]
I am looking to represent PDUs as JSON, and the most simple implementation doesn't work since codec's fields are private:

```
p := pdu.NewDeliverSM()
fields := p.Fields()
fields.Set(pdufield.ShortMessage, "ShortMessage")
bytes, err := json.Marshal(p)
log.Println(string(bytes))
```

Outputs: `{}`. I implemented my own `func (pdu *codec) MarshalJSON() ([]byte, error)` and it works only if I don't encode `TLVMap`, since it returns `unsupported type`. I don't mind this error since I can implement its own `MarshalJSON()` as well. 

The problem I am facing is with `UnmarshalJSON()`. Since I am trying to get back a `pdu.Body` and it is an interface, I need to unmarshal first to the underlying type (codec) but it is a private struct. What do you think about exposing `Codec` and its fields? Out of curiosity, what was the purpose of having `pdu.Body` as an interface?

**Comment by fiorix** [comment]
I believe what you're looking for is to convert between PDU fields and JSON. Since those two things have different *types* they need their own marshaller and unmarshaller. Look at the pdufield package and make them convertible between PDU types (fixed length, variable length, and short message) and JSON types (int, string, object). Then you can allow the pdu.Body type to be converted back and forth.

The reason pdu.Body is an interface is because SMPP is a binary protocol and all we want is to convert byte streams to Go types. We could have used reflection for that like encoding/json but that is way too slow for binary protocols. I believe what we have is the right choice for this particular protocol, but if you have suggestions I'm up for learning.
